-- Day 15 - Marketing Campaign Performance Tracking
-- Analysis queries for PostgreSQL
--
-- Important formulas:
-- CTR = clicks / impressions.
-- CPC = spend / clicks.
-- Cost per lead = spend / leads.
-- CAC = spend / acquired customers.
-- ROAS = paid revenue / spend.
-- ROI = (paid revenue - spend) / spend.
-- Revenue uses only sales where payment_status = 'paid'.

-- 1. List all marketing channels.
SELECT
    channel_id,
    channel_name,
    channel_type
FROM marketing_channels
ORDER BY channel_id;

-- 2. List all campaigns with channel information.
SELECT
    c.campaign_id,
    c.campaign_name,
    mc.channel_name,
    mc.channel_type,
    c.campaign_goal,
    c.campaign_status,
    c.budget,
    c.start_date,
    c.end_date
FROM campaigns AS c
JOIN marketing_channels AS mc
    ON c.channel_id = mc.channel_id
ORDER BY c.start_date, c.campaign_id;

-- 3. Show daily ad performance by campaign.
SELECT
    ap.performance_date,
    c.campaign_name,
    ap.impressions,
    ap.clicks,
    ap.spend
FROM ad_performance AS ap
JOIN campaigns AS c
    ON ap.campaign_id = c.campaign_id
ORDER BY ap.performance_date, c.campaign_name;

-- 4. Calculate total impressions by campaign.
SELECT
    c.campaign_id,
    c.campaign_name,
    COALESCE(SUM(ap.impressions), 0) AS total_impressions
FROM campaigns AS c
LEFT JOIN ad_performance AS ap
    ON c.campaign_id = ap.campaign_id
GROUP BY c.campaign_id, c.campaign_name
ORDER BY total_impressions DESC;

-- 5. Calculate total clicks by campaign.
SELECT
    c.campaign_id,
    c.campaign_name,
    COALESCE(SUM(ap.clicks), 0) AS total_clicks
FROM campaigns AS c
LEFT JOIN ad_performance AS ap
    ON c.campaign_id = ap.campaign_id
GROUP BY c.campaign_id, c.campaign_name
ORDER BY total_clicks DESC;

-- 6. Calculate total spend by campaign.
SELECT
    c.campaign_id,
    c.campaign_name,
    COALESCE(SUM(ap.spend), 0) AS total_spend
FROM campaigns AS c
LEFT JOIN ad_performance AS ap
    ON c.campaign_id = ap.campaign_id
GROUP BY c.campaign_id, c.campaign_name
ORDER BY total_spend DESC;

-- 7. Calculate click-through rate by campaign.
-- CTR = clicks / impressions.
SELECT
    c.campaign_id,
    c.campaign_name,
    SUM(ap.impressions) AS total_impressions,
    SUM(ap.clicks) AS total_clicks,
    ROUND(SUM(ap.clicks) * 100.0 / NULLIF(SUM(ap.impressions), 0), 2) AS ctr_percent
FROM campaigns AS c
LEFT JOIN ad_performance AS ap
    ON c.campaign_id = ap.campaign_id
GROUP BY c.campaign_id, c.campaign_name
ORDER BY ctr_percent DESC NULLS LAST;

-- 8. Calculate cost per click by campaign.
-- CPC = spend / clicks.
SELECT
    c.campaign_id,
    c.campaign_name,
    SUM(ap.spend) AS total_spend,
    SUM(ap.clicks) AS total_clicks,
    ROUND(SUM(ap.spend) / NULLIF(SUM(ap.clicks), 0), 2) AS cost_per_click
FROM campaigns AS c
LEFT JOIN ad_performance AS ap
    ON c.campaign_id = ap.campaign_id
GROUP BY c.campaign_id, c.campaign_name
ORDER BY cost_per_click ASC NULLS LAST;

-- 9. Count leads generated by campaign.
SELECT
    c.campaign_id,
    c.campaign_name,
    COUNT(l.lead_id) AS total_leads
FROM campaigns AS c
LEFT JOIN leads AS l
    ON c.campaign_id = l.campaign_id
GROUP BY c.campaign_id, c.campaign_name
ORDER BY total_leads DESC, c.campaign_name;

-- 10. Count qualified leads by campaign.
-- Converted leads are counted as qualified too because they already passed
-- the qualification step before becoming customers.
SELECT
    c.campaign_id,
    c.campaign_name,
    COUNT(l.lead_id) FILTER (
        WHERE l.lead_status IN ('qualified', 'converted')
    ) AS qualified_leads
FROM campaigns AS c
LEFT JOIN leads AS l
    ON c.campaign_id = l.campaign_id
GROUP BY c.campaign_id, c.campaign_name
ORDER BY qualified_leads DESC, c.campaign_name;

-- 11. Count customers acquired by campaign.
SELECT
    c.campaign_id,
    c.campaign_name,
    COUNT(cu.customer_id) AS acquired_customers
FROM campaigns AS c
LEFT JOIN leads AS l
    ON c.campaign_id = l.campaign_id
LEFT JOIN customers AS cu
    ON l.lead_id = cu.lead_id
GROUP BY c.campaign_id, c.campaign_name
ORDER BY acquired_customers DESC, c.campaign_name;

-- 12. Calculate lead conversion rate by campaign.
-- Lead conversion rate = qualified or converted leads / total leads.
SELECT
    c.campaign_id,
    c.campaign_name,
    COUNT(l.lead_id) AS total_leads,
    COUNT(l.lead_id) FILTER (
        WHERE l.lead_status IN ('qualified', 'converted')
    ) AS qualified_leads,
    ROUND(
        COUNT(l.lead_id) FILTER (
            WHERE l.lead_status IN ('qualified', 'converted')
        ) * 100.0
        / NULLIF(COUNT(l.lead_id), 0),
        2
    ) AS lead_conversion_rate_percent
FROM campaigns AS c
LEFT JOIN leads AS l
    ON c.campaign_id = l.campaign_id
GROUP BY c.campaign_id, c.campaign_name
ORDER BY lead_conversion_rate_percent DESC NULLS LAST;

-- 13. Calculate customer conversion rate by campaign.
-- Customer conversion rate = acquired customers / total leads.
SELECT
    c.campaign_id,
    c.campaign_name,
    COUNT(l.lead_id) AS total_leads,
    COUNT(cu.customer_id) AS acquired_customers,
    ROUND(COUNT(cu.customer_id) * 100.0 / NULLIF(COUNT(l.lead_id), 0), 2) AS customer_conversion_rate_percent
FROM campaigns AS c
LEFT JOIN leads AS l
    ON c.campaign_id = l.campaign_id
LEFT JOIN customers AS cu
    ON l.lead_id = cu.lead_id
GROUP BY c.campaign_id, c.campaign_name
ORDER BY customer_conversion_rate_percent DESC NULLS LAST;

-- 14. Calculate cost per lead.
-- Cost per lead = spend / leads.
WITH spend_by_campaign AS (
    SELECT campaign_id, SUM(spend) AS total_spend
    FROM ad_performance
    GROUP BY campaign_id
),
leads_by_campaign AS (
    SELECT campaign_id, COUNT(*) AS total_leads
    FROM leads
    GROUP BY campaign_id
)
SELECT
    c.campaign_id,
    c.campaign_name,
    COALESCE(s.total_spend, 0) AS total_spend,
    COALESCE(l.total_leads, 0) AS total_leads,
    ROUND(COALESCE(s.total_spend, 0) / NULLIF(l.total_leads, 0), 2) AS cost_per_lead
FROM campaigns AS c
LEFT JOIN spend_by_campaign AS s
    ON c.campaign_id = s.campaign_id
LEFT JOIN leads_by_campaign AS l
    ON c.campaign_id = l.campaign_id
ORDER BY cost_per_lead ASC NULLS LAST;

-- 15. Calculate customer acquisition cost.
-- CAC = spend / acquired customers.
WITH spend_by_campaign AS (
    SELECT campaign_id, SUM(spend) AS total_spend
    FROM ad_performance
    GROUP BY campaign_id
),
customers_by_campaign AS (
    SELECT l.campaign_id, COUNT(cu.customer_id) AS acquired_customers
    FROM leads AS l
    JOIN customers AS cu
        ON l.lead_id = cu.lead_id
    GROUP BY l.campaign_id
)
SELECT
    c.campaign_id,
    c.campaign_name,
    COALESCE(s.total_spend, 0) AS total_spend,
    COALESCE(cu.acquired_customers, 0) AS acquired_customers,
    ROUND(COALESCE(s.total_spend, 0) / NULLIF(cu.acquired_customers, 0), 2) AS customer_acquisition_cost
FROM campaigns AS c
LEFT JOIN spend_by_campaign AS s
    ON c.campaign_id = s.campaign_id
LEFT JOIN customers_by_campaign AS cu
    ON c.campaign_id = cu.campaign_id
ORDER BY customer_acquisition_cost ASC NULLS LAST;

-- 16. Calculate paid revenue by campaign.
-- Revenue uses only sales where payment_status = 'paid'.
SELECT
    c.campaign_id,
    c.campaign_name,
    COALESCE(SUM(s.revenue_amount) FILTER (WHERE s.payment_status = 'paid'), 0) AS paid_revenue
FROM campaigns AS c
LEFT JOIN sales AS s
    ON c.campaign_id = s.campaign_id
GROUP BY c.campaign_id, c.campaign_name
ORDER BY paid_revenue DESC;

-- 17. Calculate revenue by channel.
SELECT
    mc.channel_name,
    mc.channel_type,
    COALESCE(SUM(s.revenue_amount) FILTER (WHERE s.payment_status = 'paid'), 0) AS paid_revenue
FROM marketing_channels AS mc
LEFT JOIN campaigns AS c
    ON mc.channel_id = c.channel_id
LEFT JOIN sales AS s
    ON c.campaign_id = s.campaign_id
GROUP BY mc.channel_id, mc.channel_name, mc.channel_type
ORDER BY paid_revenue DESC;

-- 18. Calculate return on ad spend.
-- ROAS = paid revenue / spend.
WITH campaign_metrics AS (
    SELECT
        c.campaign_id,
        c.campaign_name,
        COALESCE(SUM(ap.spend), 0) AS total_spend
    FROM campaigns AS c
    LEFT JOIN ad_performance AS ap
        ON c.campaign_id = ap.campaign_id
    GROUP BY c.campaign_id, c.campaign_name
),
campaign_revenue AS (
    SELECT
        campaign_id,
        COALESCE(SUM(revenue_amount) FILTER (WHERE payment_status = 'paid'), 0) AS paid_revenue
    FROM sales
    GROUP BY campaign_id
)
SELECT
    cm.campaign_id,
    cm.campaign_name,
    cm.total_spend,
    COALESCE(cr.paid_revenue, 0) AS paid_revenue,
    ROUND(COALESCE(cr.paid_revenue, 0) / NULLIF(cm.total_spend, 0), 2) AS roas
FROM campaign_metrics AS cm
LEFT JOIN campaign_revenue AS cr
    ON cm.campaign_id = cr.campaign_id
ORDER BY roas DESC NULLS LAST;

-- 19. Calculate campaign ROI.
-- ROI = (paid revenue - spend) / spend.
WITH campaign_spend AS (
    SELECT campaign_id, SUM(spend) AS total_spend
    FROM ad_performance
    GROUP BY campaign_id
),
campaign_revenue AS (
    SELECT campaign_id, SUM(revenue_amount) FILTER (WHERE payment_status = 'paid') AS paid_revenue
    FROM sales
    GROUP BY campaign_id
)
SELECT
    c.campaign_id,
    c.campaign_name,
    COALESCE(cs.total_spend, 0) AS total_spend,
    COALESCE(cr.paid_revenue, 0) AS paid_revenue,
    ROUND((COALESCE(cr.paid_revenue, 0) - COALESCE(cs.total_spend, 0)) * 100.0 / NULLIF(cs.total_spend, 0), 2) AS roi_percent
FROM campaigns AS c
LEFT JOIN campaign_spend AS cs
    ON c.campaign_id = cs.campaign_id
LEFT JOIN campaign_revenue AS cr
    ON c.campaign_id = cr.campaign_id
ORDER BY roi_percent DESC NULLS LAST;

-- 20. Find top 5 campaigns by revenue.
WITH campaign_revenue AS (
    SELECT
        c.campaign_id,
        c.campaign_name,
        COALESCE(SUM(s.revenue_amount) FILTER (WHERE s.payment_status = 'paid'), 0) AS paid_revenue
    FROM campaigns AS c
    LEFT JOIN sales AS s
        ON c.campaign_id = s.campaign_id
    GROUP BY c.campaign_id, c.campaign_name
),
ranked_campaigns AS (
    SELECT
        *,
        RANK() OVER (ORDER BY paid_revenue DESC) AS revenue_rank
    FROM campaign_revenue
)
SELECT
    revenue_rank,
    campaign_id,
    campaign_name,
    paid_revenue
FROM ranked_campaigns
ORDER BY revenue_rank, campaign_name
LIMIT 5;

-- 21. Find top 5 campaigns by ROI.
WITH campaign_spend AS (
    SELECT campaign_id, SUM(spend) AS total_spend
    FROM ad_performance
    GROUP BY campaign_id
),
campaign_revenue AS (
    SELECT campaign_id, SUM(revenue_amount) FILTER (WHERE payment_status = 'paid') AS paid_revenue
    FROM sales
    GROUP BY campaign_id
),
campaign_roi AS (
    SELECT
        c.campaign_id,
        c.campaign_name,
        ROUND((COALESCE(cr.paid_revenue, 0) - COALESCE(cs.total_spend, 0)) * 100.0 / NULLIF(cs.total_spend, 0), 2) AS roi_percent
    FROM campaigns AS c
    LEFT JOIN campaign_spend AS cs
        ON c.campaign_id = cs.campaign_id
    LEFT JOIN campaign_revenue AS cr
        ON c.campaign_id = cr.campaign_id
)
SELECT
    RANK() OVER (ORDER BY roi_percent DESC NULLS LAST) AS roi_rank,
    campaign_id,
    campaign_name,
    roi_percent
FROM campaign_roi
ORDER BY roi_rank, campaign_name
LIMIT 5;

-- 22. Find campaigns with high spend but low revenue.
WITH campaign_spend AS (
    SELECT campaign_id, SUM(spend) AS total_spend
    FROM ad_performance
    GROUP BY campaign_id
),
campaign_revenue AS (
    SELECT campaign_id, SUM(revenue_amount) FILTER (WHERE payment_status = 'paid') AS paid_revenue
    FROM sales
    GROUP BY campaign_id
)
SELECT
    c.campaign_id,
    c.campaign_name,
    cs.total_spend,
    COALESCE(cr.paid_revenue, 0) AS paid_revenue
FROM campaigns AS c
JOIN campaign_spend AS cs
    ON c.campaign_id = cs.campaign_id
LEFT JOIN campaign_revenue AS cr
    ON c.campaign_id = cr.campaign_id
WHERE cs.total_spend >= 1500000
  AND COALESCE(cr.paid_revenue, 0) < cs.total_spend * 0.5
ORDER BY cs.total_spend DESC;

-- 23. Find campaigns with high clicks but low conversions.
WITH clicks_by_campaign AS (
    SELECT campaign_id, SUM(clicks) AS total_clicks
    FROM ad_performance
    GROUP BY campaign_id
),
conversions_by_campaign AS (
    SELECT campaign_id, COUNT(*) AS total_conversions
    FROM conversions
    GROUP BY campaign_id
)
SELECT
    c.campaign_id,
    c.campaign_name,
    cb.total_clicks,
    COALESCE(conv.total_conversions, 0) AS total_conversions
FROM campaigns AS c
JOIN clicks_by_campaign AS cb
    ON c.campaign_id = cb.campaign_id
LEFT JOIN conversions_by_campaign AS conv
    ON c.campaign_id = conv.campaign_id
WHERE cb.total_clicks >= 8000
  AND COALESCE(conv.total_conversions, 0) < 5
ORDER BY cb.total_clicks DESC;

-- 24. Find campaigns with high impressions but low click-through rate.
WITH performance AS (
    SELECT
        campaign_id,
        SUM(impressions) AS total_impressions,
        SUM(clicks) AS total_clicks
    FROM ad_performance
    GROUP BY campaign_id
)
SELECT
    c.campaign_id,
    c.campaign_name,
    p.total_impressions,
    p.total_clicks,
    ROUND(p.total_clicks * 100.0 / NULLIF(p.total_impressions, 0), 2) AS ctr_percent
FROM campaigns AS c
JOIN performance AS p
    ON c.campaign_id = p.campaign_id
WHERE p.total_impressions >= 200000
  AND p.total_clicks * 100.0 / NULLIF(p.total_impressions, 0) < 1
ORDER BY p.total_impressions DESC;

-- 25. Find campaigns with no leads.
SELECT
    c.campaign_id,
    c.campaign_name
FROM campaigns AS c
LEFT JOIN leads AS l
    ON c.campaign_id = l.campaign_id
GROUP BY c.campaign_id, c.campaign_name
HAVING COUNT(l.lead_id) = 0
ORDER BY c.campaign_id;

-- 26. Find campaigns with no paid sales.
SELECT
    c.campaign_id,
    c.campaign_name
FROM campaigns AS c
LEFT JOIN sales AS s
    ON c.campaign_id = s.campaign_id
   AND s.payment_status = 'paid'
WHERE s.sale_id IS NULL
ORDER BY c.campaign_id;

-- 27. Find best-performing channels by ROI.
WITH channel_spend AS (
    SELECT
        c.channel_id,
        SUM(ap.spend) AS total_spend
    FROM campaigns AS c
    JOIN ad_performance AS ap
        ON c.campaign_id = ap.campaign_id
    GROUP BY c.channel_id
),
channel_revenue AS (
    SELECT
        c.channel_id,
        SUM(s.revenue_amount) FILTER (WHERE s.payment_status = 'paid') AS paid_revenue
    FROM campaigns AS c
    LEFT JOIN sales AS s
        ON c.campaign_id = s.campaign_id
    GROUP BY c.channel_id
)
SELECT
    mc.channel_name,
    mc.channel_type,
    cs.total_spend,
    COALESCE(cr.paid_revenue, 0) AS paid_revenue,
    ROUND((COALESCE(cr.paid_revenue, 0) - cs.total_spend) * 100.0 / NULLIF(cs.total_spend, 0), 2) AS roi_percent,
    DENSE_RANK() OVER (
        ORDER BY (COALESCE(cr.paid_revenue, 0) - cs.total_spend) / NULLIF(cs.total_spend, 0) DESC NULLS LAST
    ) AS channel_roi_rank
FROM marketing_channels AS mc
JOIN channel_spend AS cs
    ON mc.channel_id = cs.channel_id
LEFT JOIN channel_revenue AS cr
    ON mc.channel_id = cr.channel_id
ORDER BY channel_roi_rank, mc.channel_name;

-- 28. Calculate monthly marketing spend.
SELECT
    DATE_TRUNC('month', performance_date)::date AS spend_month,
    SUM(spend) AS total_spend
FROM ad_performance
GROUP BY DATE_TRUNC('month', performance_date)::date
ORDER BY spend_month;

-- 29. Calculate monthly paid revenue from campaigns.
SELECT
    DATE_TRUNC('month', sale_date)::date AS revenue_month,
    SUM(revenue_amount) AS paid_revenue
FROM sales
WHERE payment_status = 'paid'
GROUP BY DATE_TRUNC('month', sale_date)::date
ORDER BY revenue_month;

-- 30. Calculate monthly ROI trend.
WITH monthly_spend AS (
    SELECT
        DATE_TRUNC('month', performance_date)::date AS month_start,
        SUM(spend) AS total_spend
    FROM ad_performance
    GROUP BY DATE_TRUNC('month', performance_date)::date
),
monthly_revenue AS (
    SELECT
        DATE_TRUNC('month', sale_date)::date AS month_start,
        SUM(revenue_amount) AS paid_revenue
    FROM sales
    WHERE payment_status = 'paid'
    GROUP BY DATE_TRUNC('month', sale_date)::date
)
SELECT
    ms.month_start,
    ms.total_spend,
    COALESCE(mr.paid_revenue, 0) AS paid_revenue,
    ROUND((COALESCE(mr.paid_revenue, 0) - ms.total_spend) * 100.0 / NULLIF(ms.total_spend, 0), 2) AS monthly_roi_percent
FROM monthly_spend AS ms
LEFT JOIN monthly_revenue AS mr
    ON ms.month_start = mr.month_start
ORDER BY ms.month_start;

-- 31. Find lead status distribution by campaign.
SELECT
    c.campaign_name,
    l.lead_status,
    COUNT(l.lead_id) AS lead_count
FROM campaigns AS c
LEFT JOIN leads AS l
    ON c.campaign_id = l.campaign_id
GROUP BY c.campaign_id, c.campaign_name, l.lead_status
ORDER BY c.campaign_name, lead_count DESC;

-- 32. Create a marketing campaign KPI summary using CTE.
WITH campaign_spend AS (
    SELECT campaign_id, SUM(impressions) AS total_impressions, SUM(clicks) AS total_clicks, SUM(spend) AS total_spend
    FROM ad_performance
    GROUP BY campaign_id
),
lead_metrics AS (
    SELECT
        campaign_id,
        COUNT(*) AS total_leads,
        COUNT(*) FILTER (
            WHERE lead_status IN ('qualified', 'converted')
        ) AS qualified_leads
    FROM leads
    GROUP BY campaign_id
),
customer_metrics AS (
    SELECT
        l.campaign_id,
        COUNT(cu.customer_id) AS acquired_customers
    FROM leads AS l
    JOIN customers AS cu
        ON l.lead_id = cu.lead_id
    GROUP BY l.campaign_id
),
revenue_metrics AS (
    SELECT
        campaign_id,
        SUM(revenue_amount) FILTER (WHERE payment_status = 'paid') AS paid_revenue
    FROM sales
    GROUP BY campaign_id
)
SELECT
    COUNT(*) AS total_campaigns,
    SUM(COALESCE(cs.total_spend, 0)) AS total_spend,
    SUM(COALESCE(lm.total_leads, 0)) AS total_leads,
    SUM(COALESCE(cm.acquired_customers, 0)) AS acquired_customers,
    SUM(COALESCE(rm.paid_revenue, 0)) AS paid_revenue,
    ROUND(SUM(COALESCE(rm.paid_revenue, 0)) / NULLIF(SUM(COALESCE(cs.total_spend, 0)), 0), 2) AS overall_roas,
    ROUND((SUM(COALESCE(rm.paid_revenue, 0)) - SUM(COALESCE(cs.total_spend, 0))) * 100.0 / NULLIF(SUM(COALESCE(cs.total_spend, 0)), 0), 2) AS overall_roi_percent,
    CASE
        WHEN SUM(COALESCE(rm.paid_revenue, 0)) > SUM(COALESCE(cs.total_spend, 0)) THEN 'profitable_marketing'
        WHEN SUM(COALESCE(lm.total_leads, 0)) = 0 THEN 'no_leads'
        ELSE 'needs_optimization'
    END AS marketing_health_status
FROM campaigns AS c
LEFT JOIN campaign_spend AS cs
    ON c.campaign_id = cs.campaign_id
LEFT JOIN lead_metrics AS lm
    ON c.campaign_id = lm.campaign_id
LEFT JOIN customer_metrics AS cm
    ON c.campaign_id = cm.campaign_id
LEFT JOIN revenue_metrics AS rm
    ON c.campaign_id = rm.campaign_id;

-- 33. Build a basic campaign performance dashboard view using SQL.
WITH campaign_spend AS (
    SELECT
        campaign_id,
        SUM(impressions) AS total_impressions,
        SUM(clicks) AS total_clicks,
        SUM(spend) AS total_spend
    FROM ad_performance
    GROUP BY campaign_id
),
lead_metrics AS (
    SELECT
        campaign_id,
        COUNT(*) AS total_leads,
        COUNT(*) FILTER (
            WHERE lead_status IN ('qualified', 'converted')
        ) AS qualified_leads
    FROM leads
    GROUP BY campaign_id
),
customer_metrics AS (
    SELECT
        l.campaign_id,
        COUNT(cu.customer_id) AS acquired_customers
    FROM leads AS l
    JOIN customers AS cu
        ON l.lead_id = cu.lead_id
    GROUP BY l.campaign_id
),
revenue_metrics AS (
    SELECT
        campaign_id,
        SUM(revenue_amount) FILTER (WHERE payment_status = 'paid') AS paid_revenue
    FROM sales
    GROUP BY campaign_id
),
dashboard AS (
    SELECT
        c.campaign_id,
        c.campaign_name,
        mc.channel_name,
        c.campaign_goal,
        c.campaign_status,
        COALESCE(cs.total_impressions, 0) AS total_impressions,
        COALESCE(cs.total_clicks, 0) AS total_clicks,
        COALESCE(cs.total_spend, 0) AS total_spend,
        COALESCE(lm.total_leads, 0) AS total_leads,
        COALESCE(lm.qualified_leads, 0) AS qualified_leads,
        COALESCE(cm.acquired_customers, 0) AS acquired_customers,
        COALESCE(rm.paid_revenue, 0) AS paid_revenue
    FROM campaigns AS c
    JOIN marketing_channels AS mc
        ON c.channel_id = mc.channel_id
    LEFT JOIN campaign_spend AS cs
        ON c.campaign_id = cs.campaign_id
    LEFT JOIN lead_metrics AS lm
        ON c.campaign_id = lm.campaign_id
    LEFT JOIN customer_metrics AS cm
        ON c.campaign_id = cm.campaign_id
    LEFT JOIN revenue_metrics AS rm
        ON c.campaign_id = rm.campaign_id
)
SELECT
    campaign_id,
    campaign_name,
    channel_name,
    campaign_goal,
    campaign_status,
    total_impressions,
    total_clicks,
    total_spend,
    total_leads,
    qualified_leads,
    acquired_customers,
    paid_revenue,
    ROUND(total_clicks * 100.0 / NULLIF(total_impressions, 0), 2) AS ctr_percent,
    ROUND(total_spend / NULLIF(total_clicks, 0), 2) AS cpc,
    ROUND(total_spend / NULLIF(total_leads, 0), 2) AS cost_per_lead,
    ROUND(total_spend / NULLIF(acquired_customers, 0), 2) AS customer_acquisition_cost,
    ROUND(paid_revenue / NULLIF(total_spend, 0), 2) AS roas,
    ROUND((paid_revenue - total_spend) * 100.0 / NULLIF(total_spend, 0), 2) AS roi_percent,
    CASE
        WHEN total_impressions = 0 AND total_spend = 0 THEN 'no_data'
        WHEN total_leads = 0 THEN 'no_leads'
        WHEN paid_revenue = 0 THEN 'no_sales'
        WHEN total_spend >= 1500000 AND paid_revenue < total_spend * 0.5 THEN 'high_spend_low_return'
        WHEN paid_revenue > total_spend * 1.5 THEN 'strong_roi'
        ELSE 'needs_optimization'
    END AS campaign_health_status
FROM dashboard
ORDER BY roi_percent DESC NULLS LAST, campaign_name;
