-- Day 10 - Football World Cup 2026 Dashboard
-- Real pre-tournament data for PostgreSQL
--
-- Data status as of 2026-05-19:
-- - The 48 qualified teams are confirmed.
-- - Groups and many fixture details are published by FIFA.
-- - Some associations have announced provisional or selected squads.
-- - FIFA says all squads remain provisional until the final lists are announced on 2026-06-02.
-- - Scores, goals, cards, substitutions, and match statistics are not available before matches are played.

INSERT INTO teams (team_name, confederation, group_name, coach_name) VALUES
    ('Mexico', 'CONCACAF', 'A', 'Javier Aguirre'),
    ('South Africa', 'CAF', 'A', 'Hugo Broos'),
    ('Korea Republic', 'AFC', 'A', 'Hong Myung-bo'),
    ('Czechia', 'UEFA', 'A', 'Ivan Hašek'),
    ('Canada', 'CONCACAF', 'B', 'Jesse Marsch'),
    ('Bosnia and Herzegovina', 'UEFA', 'B', 'Sergej Barbarez'),
    ('Qatar', 'AFC', 'B', 'Julen Lopetegui'),
    ('Switzerland', 'UEFA', 'B', 'Murat Yakin'),
    ('Brazil', 'CONMEBOL', 'C', 'Carlo Ancelotti'),
    ('Morocco', 'CAF', 'C', 'Walid Regragui'),
    ('Haiti', 'CONCACAF', 'C', 'Sébastien Migné'),
    ('Scotland', 'UEFA', 'C', 'Steve Clarke'),
    ('United States', 'CONCACAF', 'D', 'Mauricio Pochettino'),
    ('Paraguay', 'CONMEBOL', 'D', 'Gustavo Alfaro'),
    ('Australia', 'AFC', 'D', 'Tony Popovic'),
    ('Türkiye', 'UEFA', 'D', 'Vincenzo Montella'),
    ('Germany', 'UEFA', 'E', 'Julian Nagelsmann'),
    ('Curaçao', 'CONCACAF', 'E', 'Dick Advocaat'),
    ('Côte d''Ivoire', 'CAF', 'E', 'Emerse Faé'),
    ('Ecuador', 'CONMEBOL', 'E', 'Sebastián Beccacece'),
    ('Netherlands', 'UEFA', 'F', 'Ronald Koeman'),
    ('Japan', 'AFC', 'F', 'Hajime Moriyasu'),
    ('Sweden', 'UEFA', 'F', 'Graham Potter'),
    ('Tunisia', 'CAF', 'F', 'Sami Trabelsi'),
    ('Belgium', 'UEFA', 'G', 'Rudi Garcia'),
    ('IR Iran', 'AFC', 'G', 'Amir Ghalenoei'),
    ('Egypt', 'CAF', 'G', 'Hossam Hassan'),
    ('New Zealand', 'OFC', 'G', 'Darren Bazeley'),
    ('Spain', 'UEFA', 'H', 'Luis de la Fuente'),
    ('Uruguay', 'CONMEBOL', 'H', 'Marcelo Bielsa'),
    ('Saudi Arabia', 'AFC', 'H', 'Hervé Renard'),
    ('Cabo Verde', 'CAF', 'H', 'Bubista'),
    ('France', 'UEFA', 'I', 'Didier Deschamps'),
    ('Senegal', 'CAF', 'I', 'Pape Thiaw'),
    ('Norway', 'UEFA', 'I', 'Ståle Solbakken'),
    ('Iraq', 'AFC', 'I', 'Graham Arnold'),
    ('Argentina', 'CONMEBOL', 'J', 'Lionel Scaloni'),
    ('Austria', 'UEFA', 'J', 'Ralf Rangnick'),
    ('Algeria', 'CAF', 'J', 'Vladimir Petković'),
    ('Jordan', 'AFC', 'J', 'Jamal Sellami'),
    ('Portugal', 'UEFA', 'K', 'Roberto Martínez'),
    ('Colombia', 'CONMEBOL', 'K', 'Néstor Lorenzo'),
    ('Uzbekistan', 'AFC', 'K', 'Timur Kapadze'),
    ('Congo DR', 'CAF', 'K', 'Sébastien Desabre'),
    ('England', 'UEFA', 'L', 'Thomas Tuchel'),
    ('Croatia', 'UEFA', 'L', 'Zlatko Dalić'),
    ('Panama', 'CONCACAF', 'L', 'Thomas Christiansen'),
    ('Ghana', 'CAF', 'L', 'Otto Addo');

-- Recent/current national-team player examples.
-- These are real player names for SQL practice, but they are not official final World Cup squads.
-- The players table has squad_status/source columns so official 26-player squads can be loaded later.
-- Keep squad_status = 'recent_player_example' until final FIFA squad rows are verified.
INSERT INTO players (team_id, player_name, shirt_number, position, preferred_foot) VALUES
    (1, 'Guillermo Ochoa', 1, 'goalkeeper', 'right'),
    (1, 'Edson Álvarez', 4, 'midfielder', 'right'),
    (1, 'Raúl Jiménez', 9, 'forward', 'right'),
    (2, 'Ronwen Williams', 1, 'goalkeeper', 'right'),
    (2, 'Teboho Mokoena', 4, 'midfielder', 'right'),
    (2, 'Percy Tau', 10, 'forward', 'left'),
    (3, 'Kim Min-jae', 4, 'defender', 'right'),
    (3, 'Lee Kang-in', 18, 'midfielder', 'left'),
    (3, 'Son Heung-min', 7, 'forward', 'right'),
    (4, 'Tomáš Souček', 22, 'midfielder', 'right'),
    (4, 'Patrik Schick', 10, 'forward', 'left'),
    (4, 'Lukáš Provod', 14, 'midfielder', 'left'),
    (5, 'Alphonso Davies', 19, 'defender', 'left'),
    (5, 'Stephen Eustáquio', 7, 'midfielder', 'right'),
    (5, 'Jonathan David', 10, 'forward', 'right'),
    (6, 'Edin Džeko', 11, 'forward', 'right'),
    (6, 'Sead Kolašinac', 5, 'defender', 'left'),
    (6, 'Rade Krunić', 8, 'midfielder', 'right'),
    (7, 'Akram Afif', 11, 'forward', 'right'),
    (7, 'Almoez Ali', 19, 'forward', 'right'),
    (7, 'Hassan Al-Haydos', 10, 'midfielder', 'right'),
    (8, 'Granit Xhaka', 10, 'midfielder', 'left'),
    (8, 'Manuel Akanji', 5, 'defender', 'right'),
    (8, 'Breel Embolo', 7, 'forward', 'right'),
    (9, 'Alisson Becker', 1, 'goalkeeper', 'right'),
    (9, 'Vinícius Júnior', 7, 'forward', 'right'),
    (9, 'Rodrygo', 10, 'forward', 'right'),
    (10, 'Achraf Hakimi', 2, 'defender', 'right'),
    (10, 'Sofyan Amrabat', 4, 'midfielder', 'right'),
    (10, 'Youssef En-Nesyri', 19, 'forward', 'left'),
    (11, 'Frantzdy Pierrot', 20, 'forward', 'right'),
    (11, 'Duckens Nazon', 9, 'forward', 'right'),
    (11, 'Johny Placide', 1, 'goalkeeper', 'right'),
    (12, 'Andrew Robertson', 3, 'defender', 'left'),
    (12, 'Scott McTominay', 4, 'midfielder', 'right'),
    (12, 'John McGinn', 7, 'midfielder', 'left'),
    (13, 'Christian Pulisic', 10, 'forward', 'right'),
    (13, 'Weston McKennie', 8, 'midfielder', 'right'),
    (13, 'Tyler Adams', 4, 'midfielder', 'right'),
    (14, 'Miguel Almirón', 10, 'midfielder', 'left'),
    (14, 'Gustavo Gómez', 15, 'defender', 'right'),
    (14, 'Julio Enciso', 19, 'forward', 'right'),
    (15, 'Mathew Ryan', 1, 'goalkeeper', 'right'),
    (15, 'Jackson Irvine', 22, 'midfielder', 'right'),
    (15, 'Mitchell Duke', 15, 'forward', 'right'),
    (16, 'Hakan Çalhanoğlu', 10, 'midfielder', 'right'),
    (16, 'Arda Güler', 8, 'midfielder', 'left'),
    (16, 'Kerem Aktürkoğlu', 7, 'forward', 'right'),
    (17, 'Manuel Neuer', 1, 'goalkeeper', 'right'),
    (17, 'Joshua Kimmich', 6, 'midfielder', 'right'),
    (17, 'Jamal Musiala', 10, 'midfielder', 'right'),
    (18, 'Leandro Bacuna', 7, 'midfielder', 'right'),
    (18, 'Juninho Bacuna', 10, 'midfielder', 'right'),
    (18, 'Eloy Room', 1, 'goalkeeper', 'right'),
    (19, 'Sébastien Haller', 22, 'forward', 'right'),
    (19, 'Franck Kessié', 8, 'midfielder', 'right'),
    (19, 'Simon Adingra', 11, 'forward', 'right'),
    (20, 'Moisés Caicedo', 23, 'midfielder', 'right'),
    (20, 'Piero Hincapié', 3, 'defender', 'left'),
    (20, 'Enner Valencia', 13, 'forward', 'right'),
    (21, 'Virgil van Dijk', 4, 'defender', 'right'),
    (21, 'Frenkie de Jong', 21, 'midfielder', 'right'),
    (21, 'Cody Gakpo', 11, 'forward', 'right'),
    (22, 'Takefusa Kubo', 20, 'midfielder', 'left'),
    (22, 'Kaoru Mitoma', 7, 'forward', 'right'),
    (22, 'Wataru Endo', 6, 'midfielder', 'right'),
    (23, 'Alexander Isak', 9, 'forward', 'right'),
    (23, 'Viktor Gyökeres', 17, 'forward', 'right'),
    (23, 'Dejan Kulusevski', 21, 'midfielder', 'left'),
    (24, 'Ellyes Skhiri', 17, 'midfielder', 'right'),
    (24, 'Youssef Msakni', 7, 'forward', 'right'),
    (24, 'Aïssa Laïdouni', 14, 'midfielder', 'right'),
    (25, 'Kevin De Bruyne', 7, 'midfielder', 'right'),
    (25, 'Romelu Lukaku', 10, 'forward', 'left'),
    (25, 'Thibaut Courtois', 1, 'goalkeeper', 'left'),
    (26, 'Mehdi Taremi', 9, 'forward', 'right'),
    (26, 'Sardar Azmoun', 20, 'forward', 'right'),
    (26, 'Alireza Jahanbakhsh', 7, 'forward', 'right'),
    (27, 'Mohamed Salah', 10, 'forward', 'left'),
    (27, 'Trézéguet', 7, 'forward', 'right'),
    (27, 'Mostafa Mohamed', 11, 'forward', 'right'),
    (28, 'Chris Wood', 9, 'forward', 'right'),
    (28, 'Winston Reid', 2, 'defender', 'right'),
    (28, 'Sarpreet Singh', 10, 'midfielder', 'left'),
    (29, 'Álvaro Morata', 7, 'forward', 'right'),
    (29, 'Pedri', 8, 'midfielder', 'right'),
    (29, 'Lamine Yamal', 19, 'forward', 'left'),
    (30, 'Federico Valverde', 15, 'midfielder', 'right'),
    (30, 'Darwin Núñez', 9, 'forward', 'right'),
    (30, 'Ronald Araújo', 4, 'defender', 'right'),
    (31, 'Salem Al-Dawsari', 10, 'forward', 'right'),
    (31, 'Mohammed Al-Owais', 21, 'goalkeeper', 'right'),
    (31, 'Saleh Al-Shehri', 11, 'forward', 'right'),
    (32, 'Ryan Mendes', 20, 'forward', 'right'),
    (32, 'Bebé', 21, 'forward', 'right'),
    (32, 'Vozinha', 1, 'goalkeeper', 'right'),
    (33, 'Kylian Mbappé', 10, 'forward', 'right'),
    (33, 'Antoine Griezmann', 7, 'forward', 'left'),
    (33, 'Aurélien Tchouaméni', 8, 'midfielder', 'right'),
    (34, 'Sadio Mané', 10, 'forward', 'right'),
    (34, 'Kalidou Koulibaly', 3, 'defender', 'right'),
    (34, 'Édouard Mendy', 16, 'goalkeeper', 'right'),
    (35, 'Erling Haaland', 9, 'forward', 'left'),
    (35, 'Martin Ødegaard', 10, 'midfielder', 'left'),
    (35, 'Sander Berge', 8, 'midfielder', 'right'),
    (36, 'Aymen Hussein', 18, 'forward', 'right'),
    (36, 'Zidane Iqbal', 14, 'midfielder', 'right'),
    (36, 'Jalal Hassan', 1, 'goalkeeper', 'right'),
    (37, 'Lionel Messi', 10, 'forward', 'left'),
    (37, 'Julián Álvarez', 9, 'forward', 'right'),
    (37, 'Emiliano Martínez', 23, 'goalkeeper', 'right'),
    (38, 'David Alaba', 8, 'defender', 'left'),
    (38, 'Marcel Sabitzer', 9, 'midfielder', 'right'),
    (38, 'Marko Arnautović', 7, 'forward', 'right'),
    (39, 'Riyad Mahrez', 7, 'forward', 'left'),
    (39, 'Ismaël Bennacer', 22, 'midfielder', 'left'),
    (39, 'Youcef Belaïli', 10, 'forward', 'right'),
    (40, 'Mousa Al-Taamari', 10, 'forward', 'left'),
    (40, 'Yazan Al-Naimat', 11, 'forward', 'right'),
    (40, 'Yazeed Abu Laila', 1, 'goalkeeper', 'right'),
    (41, 'Cristiano Ronaldo', 7, 'forward', 'right'),
    (41, 'Bruno Fernandes', 8, 'midfielder', 'right'),
    (41, 'Bernardo Silva', 10, 'midfielder', 'left'),
    (42, 'Luis Díaz', 7, 'forward', 'right'),
    (42, 'James Rodríguez', 10, 'midfielder', 'left'),
    (42, 'Davinson Sánchez', 23, 'defender', 'right'),
    (43, 'Eldor Shomurodov', 14, 'forward', 'right'),
    (43, 'Abbosbek Fayzullaev', 22, 'midfielder', 'right'),
    (43, 'Utkir Yusupov', 1, 'goalkeeper', 'right'),
    (44, 'Chancel Mbemba', 22, 'defender', 'right'),
    (44, 'Cédric Bakambu', 17, 'forward', 'right'),
    (44, 'Yoane Wissa', 20, 'forward', 'right'),
    (45, 'Harry Kane', 9, 'forward', 'right'),
    (45, 'Jude Bellingham', 10, 'midfielder', 'right'),
    (45, 'Bukayo Saka', 7, 'forward', 'left'),
    (46, 'Luka Modrić', 10, 'midfielder', 'right'),
    (46, 'Joško Gvardiol', 4, 'defender', 'left'),
    (46, 'Andrej Kramarić', 9, 'forward', 'right'),
    (47, 'César Blackman', 2, 'defender', 'right'),
    (47, 'Adalberto Carrasquilla', 8, 'midfielder', 'right'),
    (47, 'José Fajardo', 17, 'forward', 'right'),
    (48, 'Mohammed Kudus', 20, 'midfielder', 'left'),
    (48, 'Thomas Partey', 5, 'midfielder', 'right'),
    (48, 'Jordan Ayew', 9, 'forward', 'right');

INSERT INTO stadiums (stadium_name, city, country, capacity) VALUES
    ('Mexico City Stadium', 'Mexico City', 'Mexico', 87523),
    ('Estadio Guadalajara', 'Guadalajara', 'Mexico', 49850),
    ('Estadio Monterrey', 'Monterrey', 'Mexico', 53500),
    ('Toronto Stadium', 'Toronto', 'Canada', 45500),
    ('BC Place Vancouver', 'Vancouver', 'Canada', 54500),
    ('Los Angeles Stadium', 'Los Angeles', 'United States', 70240),
    ('San Francisco Bay Area Stadium', 'Santa Clara', 'United States', 68500),
    ('Seattle Stadium', 'Seattle', 'United States', 69000),
    ('Dallas Stadium', 'Dallas', 'United States', 80000),
    ('Houston Stadium', 'Houston', 'United States', 72220),
    ('Kansas City Stadium', 'Kansas City', 'United States', 76500),
    ('Atlanta Stadium', 'Atlanta', 'United States', 71000),
    ('Miami Stadium', 'Miami', 'United States', 64767),
    ('Boston Stadium', 'Boston', 'United States', 65878),
    ('Philadelphia Stadium', 'Philadelphia', 'United States', 67594),
    ('New York New Jersey Stadium', 'New York New Jersey', 'United States', 82500);

-- Official fixture sample from FIFA's published schedule page.
-- Scores and winners are NULL because these matches have not been played yet.
INSERT INTO matches (
    match_date,
    stage,
    stadium_id,
    home_team_id,
    away_team_id,
    home_score,
    away_score,
    winner_team_id,
    attendance,
    match_status
) VALUES
    ('2026-06-11', 'group_stage', 1, 1, 2, NULL, NULL, NULL, NULL, 'scheduled'),
    ('2026-06-11', 'group_stage', 2, 3, 4, NULL, NULL, NULL, NULL, 'scheduled'),
    ('2026-06-12', 'group_stage', 4, 5, 6, NULL, NULL, NULL, NULL, 'scheduled'),
    ('2026-06-12', 'group_stage', 6, 13, 14, NULL, NULL, NULL, NULL, 'scheduled'),
    ('2026-06-13', 'group_stage', 14, 11, 12, NULL, NULL, NULL, NULL, 'scheduled'),
    ('2026-06-13', 'group_stage', 5, 15, 16, NULL, NULL, NULL, NULL, 'scheduled'),
    ('2026-06-13', 'group_stage', 16, 9, 10, NULL, NULL, NULL, NULL, 'scheduled'),
    ('2026-06-13', 'group_stage', 7, 7, 8, NULL, NULL, NULL, NULL, 'scheduled'),
    ('2026-06-14', 'group_stage', 15, 19, 20, NULL, NULL, NULL, NULL, 'scheduled'),
    ('2026-06-14', 'group_stage', 10, 17, 18, NULL, NULL, NULL, NULL, 'scheduled'),
    ('2026-06-14', 'group_stage', 9, 21, 22, NULL, NULL, NULL, NULL, 'scheduled'),
    ('2026-06-14', 'group_stage', 3, 23, 24, NULL, NULL, NULL, NULL, 'scheduled');
